apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VijayaRL/react-app.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles: 
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: react-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: false 
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true